package Phase2;

public enum NodeType {
    ASSIGNMENT,
    BOOLEANEXPRESSION,
    CONSTANT,
    DOUBLEEXPRESSION,
    ENDSTATEEMENT,
    EXPRESSION,
    FUNCTIONRETURN,
    IDKEYWORD,
    INFORMATION,
    INTEGEREXPRESSION,
    OP,
    PARAMS,
    PARAMST,
    RELOP,
    STRINGEXPRESSION,
    STRINGLITERAL,
    TYPE,
    VARDECLARATION
}
